### ISSUE TITLE
invalid byte sequence in US-ASCII (ArgumentError) when file have accents / UTF-8 chars

### ISSUE THREAD

**Issue by blvz** [slim-template/haml2slim#15]
it's breaking on Ruby 1.9, when converting HAML files that use accents, for example.

```
/Users/rafaelb/.rvm/gems/ruby-1.9.3-p194@new21ettr/gems/haml2slim-0.4.6/lib/haml2slim/converter.rb:18:in `[]': invalid byte sequence in US-ASCII (ArgumentError)
    from /Users/rafaelb/.rvm/gems/ruby-1.9.3-p194@new21ettr/gems/haml2slim-0.4.6/lib/haml2slim/converter.rb:18:in `parse_line'
    from /Users/rafaelb/.rvm/gems/ruby-1.9.3-p194@new21ettr/gems/haml2slim-0.4.6/lib/haml2slim/converter.rb:8:in `block in initialize'
    from /Users/rafaelb/.rvm/gems/ruby-1.9.3-p194@new21ettr/gems/haml2slim-0.4.6/lib/haml2slim/converter.rb:7:in `each_line'
    from /Users/rafaelb/.rvm/gems/ruby-1.9.3-p194@new21ettr/gems/haml2slim-0.4.6/lib/haml2slim/converter.rb:7:in `initialize'
    from /Users/rafaelb/.rvm/gems/ruby-1.9.3-p194@new21ettr/gems/haml2slim-0.4.6/lib/haml2slim.rb:6:in `new'
    from /Users/rafaelb/.rvm/gems/ruby-1.9.3-p194@new21ettr/gems/haml2slim-0.4.6/lib/haml2slim.rb:6:in `convert!'
    from /Users/rafaelb/.rvm/gems/ruby-1.9.3-p194@new21ettr/gems/haml2slim-0.4.6/lib/haml2slim/command.rb:75:in `_process'
    from /Users/rafaelb/.rvm/gems/ruby-1.9.3-p194@new21ettr/gems/haml2slim-0.4.6/lib/haml2slim/command.rb:55:in `block in process!'
    from /Users/rafaelb/.rvm/gems/ruby-1.9.3-p194@new21ettr/gems/haml2slim-0.4.6/lib/haml2slim/command.rb:55:in `each'
    from /Users/rafaelb/.rvm/gems/ruby-1.9.3-p194@new21ettr/gems/haml2slim-0.4.6/lib/haml2slim/command.rb:55:in `process!'
    from /Users/rafaelb/.rvm/gems/ruby-1.9.3-p194@new21ettr/gems/haml2slim-0.4.6/lib/haml2slim/command.rb:14:in `run'
    from /Users/rafaelb/.rvm/gems/ruby-1.9.3-p194@new21ettr/gems/haml2slim-0.4.6/bin/haml2slim:7:in `<top (required)>'
    from /Users/rafaelb/.rvm/gems/ruby-1.9.3-p194@new21ettr/bin/haml2slim:19:in `load'
    from /Users/rafaelb/.rvm/gems/ruby-1.9.3-p194@new21ettr/bin/haml2slim:19:in `<main>'
    from /Users/rafaelb/.rvm/gems/ruby-1.9.3-p194@new21ettr/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/rafaelb/.rvm/gems/ruby-1.9.3-p194@new21ettr/bin/ruby_noexec_wrapper:14:in `<main>'
```

**Comment by ilnurnasyrov** [comment]
http://stackoverflow.com/questions/17031651/invalid-byte-sequence-in-us-ascii-argument-error-when-i-run-rake-dbseed-in-ra
